---
title: "Next Word Text Prediction App Presentation"
author: "Olivier DANCOT"
highlighter: highlight.js
output: pdf_document
job: Data Analyst Freelance
knit: slidify::knit2slides
mode: selfcontained
hitheme: tomorrow
subtitle: App for Data Science Capstone from Coursera
framework: io2012
widgets: []
---

## Next Word Text Prediction App Presentation

Welcome on the Slidify Presentation of my App for Coursera Data Science Capstone Projetc. You should find more information about it on the next slide. 

*Thank's for reading*

--- .class #id 

## What is the Next Word Text Prediction ShinyApp ? 

I made this App to predict the next word when you type a serie of word. As for mobile text messaging, this app give the 4 most relevant next word after the serie of words before. 

You just have to write down one or more words and you'll find the next one ! 

As simple as it seems :) 


--- .class #id 

## Library & Algorithm 

I used 2 library to do this app : 
- shiny
- data.table

Then I Load data sets and I parse and split data to create clean data set. 

Next I create the full algorythm : 
- I filter unknown words
- I create N Grams to find lenght
- I find the top words

Finaly I aggregate Words and Predict the most relevant on the application. 


--- .class #id 


## UI.R

I put all information on how to use the app on Sidebar Panel and the box for text input on the main panel, it is the easier user experience way for this application. 


--- .class #id 

## On ShinyApps

Application is really easy to use. 

You can find some explaination about how it work on the page of the app itself : 
**http://odancot.shinyapps.io/DataScienceCapstone**

In resume : quite a simple application but usefull to save time when typing texts. 

**Hope you enjoy it !**

--- .class #id 